{
 "title": "KubeDB / MySQL / Summary",
 "description": "The dashboard is designed for KubeDB managed MariaDB",
 "tags": [
  "db",
  "stats",
  "kubedb",
  "mariadb"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   { "name": "namespace", "label": "Namespace", "query": "label_values(namespace)" },
   {
    "name": "db",
    "label": "mysql",
    "query": "label_values(kubedb_mysql_status_phase{namespace=~\"$namespace\"},mysql)"
   }
  ]
 },
 "panels": [
  { "title": "General Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Database Status",
   "type": "stat",
   "description": "Represent database status",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kubedb_mysql_status_phase{namespace=\"$namespace\", mysql=\"$db\"} == 1\n",
     "legendFormat": "{{phase}}"
    }
   ]
  },
  {
   "title": "Version",
   "type": "stat",
   "description": "MariaDB CR Name",
   "gridPos": { "h": 3, "w": 5, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "kubedb_mysql_info{namespace=\"$namespace\", mysql=\"$db\"}",
     "legendFormat": "{{ version }}"
    }
   ]
  },
  {
   "title": "User Address Type",
   "type": "stat",
   "description": "MariaDB CR Name",
   "gridPos": { "h": 3, "w": 5, "x": 11, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "kubedb_mysql_info{namespace=\"$namespace\", mysql=\"$db\"}",
     "legendFormat": "{{ useAddressType }}"
    }
   ]
  },
  {
   "title": "Require Secure Transport",
   "type": "stat",
   "description": "When this option is enabled, connections attempted using insecure transport will be rejected.",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kubedb_mysql_info{namespace=\"$namespace\", mysql=\"$db\"}",
     "legendFormat": "{{requireSSL}}"
    }
   ]
  },
  {
   "title": "Termination Policy",
   "type": "stat",
   "description": "KubeDB Database Resource terminationPolicy",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kubedb_mysql_info{namespace=\"$namespace\", mysql=\"$db\"}",
     "legendFormat": "{{terminationPolicy}}"
    }
   ]
  },
  {
   "title": "Total Nodes",
   "type": "stat",
   "description": "Total node count of MariaDB cluster",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kubedb_mysql_replicas{namespace=\"$namespace\",mysql=\"$db\"}"
    }
   ]
  },
  {
   "title": "CPU Request (Core)",
   "type": "stat",
   "description": "Initial Requested CPU amount by MariaDB Instance",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kubedb_mysql_resource_request_cpu{namespace=\"$namespace\", mysql=\"$db\"}"
    }
   ]
  },
  {
   "title": "CPU Limit (Core)",
   "type": "stat",
   "description": "CPU Limit in core by MariaDB instance",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kubedb_mysql_resource_limit_cpu{namespace=\"$namespace\", mysql=\"$db\"}"
    }
   ]
  },
  {
   "title": "Memory Request",
   "type": "stat",
   "description": "Initial Requested Memory amount by MariaDB Instance",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kubedb_mysql_resource_request_memory{namespace=\"$namespace\", mysql=\"$db\"}"
    }
   ]
  },
  {
   "title": "Memory Limit",
   "type": "stat",
   "description": "KubeDB mariadb Total Memory Limit",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kubedb_mysql_resource_limit_memory{namespace=\"$namespace\", mysql=\"$db\"}"
    }
   ]
  },
  {
   "title": "Storage Request",
   "type": "stat",
   "description": "Total storage request by mariadb nodes",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kubedb_mysql_resource_request_storage{namespace=\"$namespace\", mysql=\"$db\"}"
    }
   ]
  },
  { "title": "CPU Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "CPU Usage",
   "type": "graph",
   "description": "CPU Usage by MariaDB pods",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{namespace=\"$namespace\", pod=~\"$db-.*\"}) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "CPU Quota",
   "type": "table",
   "description": "CPU Quote information in details",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{namespace=\"$namespace\", pod=~\"$db.*\"}) by (pod)"
    },
    {
     "expr": "sum(cluster:namespace:pod_cpu:active:kube_pod_container_resource_requests{namespace=\"$namespace\", pod=~\"$db.*\"}) by (pod)"
    },
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{namespace=\"$namespace\", pod=~\"$db.*\"}) by (pod) / sum(cluster:namespace:pod_cpu:active:kube_pod_container_resource_requests{namespace=\"$namespace\", pod=~\"$db.*\"}) by (pod)"
    },
    {
     "expr": "sum(cluster:namespace:pod_cpu:active:kube_pod_container_resource_limits{namespace=\"$namespace\", pod=~\"$db.*\"}) by (pod)"
    },
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{namespace=\"$namespace\", pod=~\"$db.*\"}) by (pod) / sum(cluster:namespace:pod_cpu:active:kube_pod_container_resource_limits{namespace=\"$namespace\", pod=~\"$db.*\"}) by (pod)"
    }
   ]
  },
  { "title": "Memory Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "Memory Usage",
   "type": "graph",
   "description": "Memory Usage by MariaDB pods",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(node_namespace_pod_container:container_memory_working_set_bytes{namespace=\"$namespace\", pod=~\"$db-.*\",container!=\"\"}) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Memory Quota",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=\"$namespace\",pod=~\"$db.*\",container!=\"\", image!=\"\"}) by (pod)"
    },
    {
     "expr": "sum(cluster:namespace:pod_memory:active:kube_pod_container_resource_requests{namespace=\"$namespace\",pod=~\"$db.*\"}) by (pod)"
    },
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=\"$namespace\",pod=~\"$db.*\",container!=\"\", image!=\"\"}) by (pod) / sum(cluster:namespace:pod_memory:active:kube_pod_container_resource_requests{namespace=\"$namespace\",pod=~\"$db.*\"}) by (pod)"
    },
    {
     "expr": "sum(cluster:namespace:pod_memory:active:kube_pod_container_resource_limits{namespace=\"$namespace\",pod=~\"$db.*\"}) by (pod)"
    },
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=\"$namespace\",pod=~\"$db.*\",container!=\"\", image!=\"\"}) by (pod) / sum(cluster:namespace:pod_memory:active:kube_pod_container_resource_limits{namespace=\"$namespace\", pod=~\"$db.*\"}) by (pod)"
    },
    {
     "expr": "sum(container_memory_rss{namespace=\"$namespace\",pod=~\"$db.*\",container!=\"\"}) by (pod)"
    },
    {
     "expr": "sum(container_memory_cache{namespace=\"$namespace\",pod=~\"$db.*\",container!=\"\"}) by (pod)"
    },
    {
     "expr": "sum(container_memory_swap{namespace=\"$namespace\",pod=~\"$db.*\",container!=\"\"}) by (pod)"
    }
   ]
  },
  { "title": "Storage Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "Disk Usage",
   "type": "graph",
   "description": "Disk usage by MariaDB pods",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "avg(container_blkio_device_usage_total{namespace=\"$namespace\", pod=~\"$db-.*\"}) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Disk R/W Info",
   "type": "graph",
   "description": "System Disk Usage Information",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_fs_writes_total{namespace=\"$namespace\", pod=~\"$db-.*\"}[5m]))by(pod)",
     "legendFormat": "{{pod}}-disk-write"
    },
    {
     "expr": "sum(rate(container_fs_reads_total{namespace=\"$namespace\", pod=~\"$db-.*\"}[5m]))by(pod)",
     "legendFormat": "{{pod}}-disk-read"
    }
   ]
  },
  {
   "title": "IOPS (Reads+Writes)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ceil(sum by(pod) (rate(container_fs_reads_total{container!=\"\", namespace=~\"$namespace\", pod=~\"$db.*\"}[5m]) + rate(container_fs_writes_total{container!=\"\" ,namespace=~\"$namespace\", pod=~\"$db.*\"}[5m])))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "ThroughPut (Read+Write)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum by(pod) (rate(container_fs_reads_bytes_total{container!=\"\", namespace=~\"$namespace\", pod=~\"$db.*\"}[5m]) + rate(container_fs_writes_bytes_total{container!=\"\" ,namespace=~\"$namespace\", pod=~\"$db.*\"}[5m]))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Current Storage IO",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(pod) (rate(container_fs_reads_total{container!=\"\", pod=~\"$db.*\",namespace=~\"$namespace\"}[5m]))"
    },
    {
     "expr": "sum by(pod) (rate(container_fs_writes_total{container!=\"\", pod=~\"$db.*\",namespace=~\"$namespace\"}[5m]))"
    },
    {
     "expr": "sum by(pod) (rate(container_fs_reads_total{container!=\"\", pod=~\"$db.*\",namespace=~\"$namespace\"}[5m]) + rate(container_fs_writes_total{container!=\"\",pod=~\"$db.*\",namespace=~\"$namespace\"}[5m]))"
    },
    {
     "expr": "sum by(pod) (rate(container_fs_reads_bytes_total{container!=\"\", pod=~\"$mariadb.*\",namespace=~\"$namespace\"}[5m]))"
    },
    {
     "expr": "sum by(pod) (rate(container_fs_writes_bytes_total{container!=\"\", pod=~\"$mariadb.*\",namespace=~\"$namespace\"}[5m]))"
    },
    {
     "expr": "sum by(pod) (rate(container_fs_reads_bytes_total{container!=\"\", pod=~\"$mariadb.*\",namespace=~\"$namespace\"}[5m]) + rate(container_fs_writes_bytes_total{container!=\"\",pod=~\"$mariadb.*\",namespace=~\"$namespace\"}[5m]))"
    }
   ]
  },
  { "title": "Network Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 58 } },
  {
   "title": "Receive Bandwidth",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 59 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(container_network_receive_bytes_total{namespace=~\"$namespace\", pod=~\"$db.*\"}[$__rate_interval])) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Transmit Bandwidth",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(container_network_transmit_bytes_total{namespace=~\"$namespace\", pod=~\"$db.*\"}[$__rate_interval])) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  }
 ]
}